site_name: MajorDom Docs
site_url: https://docs.majordom.io
site_author: Mark Parker
site_description: MajorDom documentation

copyright: Copyright &copy; MajorDom

nav:
  - Architecture Overview: 'architecture.md'
  - Custom Device: 'custom-device.md'
  - API:
    - Cloud API: 'api/cloud.md'
    - Bridge API: 'api/bridge.md'
    - Hub API: 'api/hub.md'
  - Hub Development:
    - How to Start: 'hub-development/how-to-start.md'
    - Repo Architecture: 'hub-development/repo-architecture.md'

theme:
  name: material
  custom_dir: overrides
  language: en

  features:
    - header.autohide
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.tob
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette: 

    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   primary: orange
    #   accent: orange
    #   scheme: default
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: orange
      accent: orange
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: orange
      accent: orange
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to system preference

extra:
  generator: false
  
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ParkerIndustries
  
  features:
    - navigation.footer

  analytics:
    provider: google
    property: G-NMVH5RVSYB

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true

plugins:
  - offline
  - search
  # - social
  # - optimize
  # - tags
  - swagger-ui-tag
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
