site_name: MajorDom Docs
site_url: https://docs.majordom.io
site_author: Mark Parker
site_description: MajorDom documentation

copyright: Copyright &copy; 2024 Parker Industries Inc. All rights reserved.

nav:
  - MajorDom Docs: "index.md"
  - Device Integration:
      - Overview: "device-integration/index.md"
      - Implementing a Controller: "device-integration/controller.md"
      - Storing Data: "device-integration/storing_data.md"
      - Data Models: "device-integration/data_models.md"
      - Discovery Services:
          - Overview: "device-integration/discovery/index.md"
          - Zeroconf / mDNS: "device-integration/discovery/zeroconf.md"
          - SSDP / UPnP: "device-integration/discovery/ssdp.md"
          - BLE: "device-integration/discovery/ble.md"
  - API:
      - Hub API: "api/hub.md"
      - Bridge API: "api/bridge.md"
      - Cloud API: "api/cloud.md"
  - legacy:
      - Architecture Overview: "architecture.md"
      - "Hub Development: How to Start": "hub-development/how-to-start.md"
      - Custom Merlin Device: "custom-device-legacy.md"

theme:
  name: material
  custom_dir: overrides
  language: en
  favicon: img/favicon.png

  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   primary: orange
    #   accent: orange
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: orange
      accent: orange
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: orange
      accent: orange
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference

extra:
  generator: false

  social:
    - icon: majordom/logo
      link: https://majordom.io
    - icon: fontawesome/brands/github
      link: https://github.com/ParkerIndustries
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/majordom_io
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/majordom_io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/majordom-io
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@majordom_io
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@majordom_io

  features:
    - navigation.footer

  analytics:
    provider: google
    property: G-NMVH5RVSYB

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - social
  # - optimize
  # - tags
  - swagger-ui-tag
  - git-revision-date-localized:
      enable_creation_date: true
      # enable_git_follow: false
      type: timeago
